# Generated by Django 5.1.2 on 2024-12-03 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createevent',
            name='event_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='event_time',
            field=models.TimeField(),
        ),
    ]
