# Generated by Django 5.1.2 on 2024-12-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_be_an_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='be_an_organizer',
            name='website',
        ),
    ]
