# Generated by Django 5.1.2 on 2024-12-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_be_an_organizer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='be_an_organizer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
