# Generated by Django 5.1.2 on 2024-12-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_be_an_organizer_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='be_an_organizer',
            old_name='email',
            new_name='organization_email',
        ),
    ]
