# Generated by Django 5.1.2 on 2024-12-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_be_an_organizer_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createevent',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
