# Generated by Django 5.1.2 on 2024-12-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_createevent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
