# Generated by Django 5.1.2 on 2024-12-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_createevent_total_ticket_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
