# Generated by Django 5.1.2 on 2024-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ticket_total_price_alter_ticket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='total_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
