# Generated by Django 5.1.2 on 2024-12-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_createevent_total_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
