# Generated by Django 5.1.2 on 2024-12-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_createevent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('Door sale', 'Door sale'), ('Khalti', 'Khalti')], default='Door Sale', max_length=20),
        ),
    ]
