# Generated by Django 5.1.2 on 2024-12-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_createevent_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='event_category',
            field=models.CharField(choices=[('Concert', 'Concert'), ('Trade', 'Trade')], default='Concert', max_length=255),
        ),
    ]
