# Generated by Django 5.1.2 on 2024-12-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_tradeevent_alter_createevent_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeevent',
            old_name='buyer',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='tradeevent',
            old_name='seller',
            new_name='company_name',
        ),
    ]
