# Generated by Django 5.1.2 on 2024-12-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_seller_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='scheduled_time',
            field=models.TimeField(),
        ),
    ]
