# Generated by Django 5.1.2 on 2024-12-25 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='core.createevent'),
        ),
    ]
