# Generated by Django 5.1.2 on 2024-12-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_seller_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
