# Generated by Django 5.1.2 on 2024-12-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_buyer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
