# Generated by Django 5.1.2 on 2024-12-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_name_buyer_first_name_buyer_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='name',
            new_name='full_name',
        ),
    ]
