# Generated by Django 5.1.2 on 2024-12-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_buyer_user_alter_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='event',
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
