# Generated by Django 5.1.2 on 2024-12-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_seller_event_alter_seller_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
